### ISSUE TITLE
Update page for Apolo kernel

### ISSUE THREAD

**Issue by gsstudios** [chhapil/chhapil.github.io#1]
You forgot to update your github page to give users link to kernel releases :)

**Comment by chhapil** [comment]
:) WIP

**Comment by chhapil** [comment]
done

On Sat, May 7, 2016 at 1:48 PM, Josh notifications@github.com wrote:

> You forgot to update your github page to give users link to kernel
> releases :)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/chhapil/chhapil.github.io/issues/1

## 

Thanks & Regards
Ruturaj
